#!/usr/bin/env python3
"""Regenerate docs/games-data.js for the Pixl8 site games showcase.

Source of truth = the .mp4 files in docs/games/. For each clip <id>.mp4 we pull
the title / author / BBS pid from the game's .nfo in the Pixl8 app's bundled
featured assets, then write a title-sorted window.PIXL8_GAMES array.

Run after adding a new <id>.mp4 (+ its poster and label). See the
`add-featured-game` skill for the full pipeline.
"""
import os, glob, json, sys

SITE = os.environ.get("PIXL8_SITE",
    "/home/devlin/retro/pixl8-site/docs")
FEATURED = os.environ.get("PIXL8_FEATURED",
    "/home/devlin/retro/pixl8/app/src/main/assets/featured")

# A handful of legacy carts ship the video under a friendly name but the .nfo
# under the numeric BBS id (or a variant lid). New games normally need NO entry
# here — the video id matches the .nfo name directly.
ALIAS = {
    "celeste": "15133", "wormnomnom": "23208", "spaceman8": "37216",
    "8legstolove": "41422", "justoneboss": "49232", "brekouthero": "53976",
    "picocheckmate": "54038", "rolly": "54262", "maichan": "56576",
    "kalikan": "kalikan_menu", "birdswithgunsbas": "birdswithguns",
}

def nfo_meta(name):
    p = os.path.join(FEATURED, name + ".nfo")
    if not os.path.isfile(p):
        return None
    d = {}
    for line in open(p, encoding="utf-8", errors="replace"):
        for k in ("title", "author", "mid"):
            if line.startswith(k + ":"):
                d[k] = line[len(k) + 1:].strip()
    return d

def main():
    vids = sorted(f[:-4] for f in os.listdir(os.path.join(SITE, "games"))
                  if f.endswith(".mp4"))
    if not vids:
        sys.exit("no .mp4 files in " + os.path.join(SITE, "games"))

    games, problems = [], []
    for v in vids:
        key = ALIAS.get(v, v)
        m = nfo_meta(key)
        if not m or not m.get("title"):
            problems.append(f"{v}: no .nfo/title (looked for '{key}.nfo' in featured/)")
            m = m or {}
        for kind, ext in (("posters", ".jpg"), ("labels", ".png")):
            if not os.path.isfile(os.path.join(SITE, "games", kind, v + ext)):
                problems.append(f"{v}: missing {kind}/{v}{ext}")
        games.append({
            "file": v + ".mp4",
            "title": m.get("title", v),
            "author": m.get("author", ""),
            "bbs": m.get("mid", ""),
        })

    games.sort(key=lambda g: g["title"].lower())
    out = os.path.join(SITE, "games-data.js")
    with open(out, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by tools/gen-games-data.py from the app's featured .nfo\n")
        f.write("// metadata (title/author/mid). Do not hand-edit; re-run the generator.\n")
        f.write("// bbs = .nfo `mid`; BBS page = https://www.lexaloffle.com/bbs/?pid=<bbs>\n")
        f.write("window.PIXL8_GAMES = " + json.dumps(games, ensure_ascii=False, indent=2) + ";\n")

    print(f"wrote {len(games)} games -> {out}")
    if problems:
        print("PROBLEMS (fix before shipping):")
        for p in problems:
            print("  -", p)
        sys.exit(1)

if __name__ == "__main__":
    main()
